plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    alias(libs.plugins.kotlinParcelize)
    alias(libs.plugins.kotlinKapt)
    alias(libs.plugins.hilt)
    alias(libs.plugins.composeCompiler)
}

def getApiKey() {
    def keysProperties = new Properties()
    keysProperties.load(project.rootProject.file("local.properties").newDataInputStream())
    def ApiKey = keysProperties.getProperty("news_api_key", "")
    return ApiKey
}

android {
    namespace 'com.segunfrancis.newsfeed'
    compileSdk = 37

    defaultConfig {
        applicationId "com.segunfrancis.newsfeed"
        minSdk 23
        targetSdk = 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation"  : "$projectDir/schemas".toString(),
                        "room.incremental"     : "true",
                        "room.expandProjection": "true"
                ]
            }
        }
    }

    buildTypes {
        debug {
            buildConfigField("String", "NEWS_API_KEY", getApiKey())
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField("String", "NEWS_API_KEY", getApiKey())
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
        buildConfig true
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }
}

dependencies {
    coreLibraryDesugaring libs.androidxAndroidDesugarLibs
    implementation libs.androidxCoreKtx
    implementation libs.androidxActivityCompose
    implementation libs.bundles.lifecycle
    implementation libs.kotlinxSerializationJson

    // --- Jetpack Compose Bill of Materials (BOM) ---
    implementation platform(libs.androidxComposeBom)
    testImplementation platform(libs.androidxComposeBom)
    androidTestImplementation platform(libs.androidxComposeBom)

    // Material 3 & Compose Components (Versions managed by BOM)
    implementation libs.bundles.compose
    androidTestImplementation libs.androidxComposeUiTestJunit4
    debugImplementation libs.androidxComposeUiTooling
    debugImplementation libs.androidxComposeUiTestManifest

    // Navigation & Coroutines
    implementation libs.kotlinxCoroutinesAndroid
    implementation libs.androidxNavigationCompose

    // Networking
    implementation libs.bundles.networking

    // Media Pipeline & Diagnostics
    implementation libs.coilCompose
    implementation libs.timber

    // Dagger Hilt Dependency Engine & WorkManager
    implementation libs.bundles.hilt
    kapt libs.hiltCompiler
    kapt libs.androidxHiltCompiler
    implementation libs.androidxWorkRuntimeKtx

    // Room Storage Layers
    implementation libs.bundles.room
    kapt libs.androidxRoomCompiler

    // Pagination & Supporting Jetpack Frameworks
    implementation libs.bundles.paging
    implementation libs.lottieCompose
    implementation libs.androidxDatastorePreferences
    implementation libs.androidxBrowser
    implementation libs.androidxConstraintlayoutCompose

    // Mock Testing Frameworks
    testImplementation libs.junitJupiter
    testImplementation libs.junit
    androidTestImplementation libs.androidxTestExtJunit
    androidTestImplementation libs.androidxRoomTesting
    androidTestImplementation libs.androidxTestEspressoCore
}

kapt {
    correctErrorTypes true
}

configurations.configureEach {
    resolutionStrategy {
        force libs.hiltAndroid
    }
}
